Make Sequencer emit redstone signal when at end of tape
malte0811/ControlEngineering pull request #30
Opened 2022-05-21 16:48 UTC by keifhausin

Closes #25

2022-05-22 09:42 UTC, malte0811 requested changes
Two additional points:
1. Please ask me before implementing features in the future (comment on the issue in question). In some cases I have my own "little ideas" about how a feature should be implemented.
2. Before I start debugging this in more detail, do you know why the Github actions didn't run on your commits? As far as I can tell `push` should have run on your commits even though they are in a fork.

2022-05-22 16:47 UTC, keifhausin commented
Sorry for not asking in the ticket first, ill do that in future.
The Github actions didn't run in my repo on push is Github auto disables actions in forks, as for why it didn't run on the PR I think that's because PR creation uses a different action type. looks like it uses `pull_request` https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request.

2022-05-22 16:53 UTC, keifhausin commented on src/main/java/malte0811/controlengineering/blockentity/tape/SequencerBlockEntity.java
> +                level.setBlockAndUpdate(worldPosition, blockState.setValue(SequencerBlock.HALTED, true));
Fixed the tabs everywhere.

2022-05-22 16:54 UTC, keifhausin commented on src/main/java/malte0811/controlengineering/blockentity/tape/SequencerBlockEntity.java
> +            	level.setBlockAndUpdate(worldPosition, blockState.setValue(SequencerBlock.HALTED, false));
Added checks to only change it if it needs to be changed

2022-05-22 17:04 UTC, keifhausin commented on src/main/java/malte0811/controlengineering/blocks/tape/SequencerBlock.java
> +    	return facing != null &&( facing == direction || facing == direction.getCounterClockWise() );
removed the null checks and fixed the formatting

2022-05-22 17:08 UTC, keifhausin commented on src/main/java/malte0811/controlengineering/blocks/logic/LogicCabinetBlock.java
> +    	return isMaster(state) && facing != null && facing == direction.getCounterClockWise();
I added the equivalent function to the LogicCabinetBlock and used that.  I removed the `leftIfNonMirrored` parameter from the block version as it felt redundant to hard code a `true` in the only call to that function.

2022-05-23 07:23 UTC, malte0811 commented
> Github auto disables actions in forks

Good to know, I was quite sure I had used actions in forks before… Maybe it changed at some point, or I'd enabled some option on those forks that I forgot about. I'll add the PR trigger as well.

Thanks for implementing this!

2022-05-23 07:23 UTC, merged